<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
OPENAI_API_KEY = "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"
=======
OPENAI_API_KEY = "sk-proj-nsJb8ICD7OEXNdvuUMsgT3BlbkFJjQLKNUnCid5UgFAQmwHO"
>>>>>>> 16dec33 (modifique requirements y visbot deprecado)
=======
OPENAI_API_KEY = "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"
>>>>>>> 5548ef5 (actualizacion de apikey)
=======
OPENAI_API_KEY = "sk-proj-nsJb8ICD7OEXNdvuUMsgT3BlbkFJjQLKNUnCid5UgFAQmwHO"
>>>>>>> 16dec3387abe0001d377ddafc9b56a0446b5e50a
